@echo off
echo 🚀 ebfic Business Manager - Building Professional App...
echo 🧹 Cleaning project...
call flutter clean
echo 📦 Getting dependencies...
call flutter pub get
echo 💻 Building Windows Application...
call flutter build windows --release
echo 📦 Creating MSIX Installer...
call dart run msix:create
echo ✅ Success! Your installer is ready in build\windows\x64\runner\Release\
pause
