name: Deploy EBM Control Panel to Hostinger

on:
  push:
    paths:
      - 'ebm_control/**' # শুধুমাত্র এই ফোল্ডারে কাজ করলে এটি রান হবে
    branches:
      - main

jobs:
  build-and-deploy-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Admin Panel
        run: |
          cd ebm_control
          flutter pub get
          flutter build web --release --base-href "/"

      - name: Deploy to Hostinger via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete --timeout=60"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: "/home/u200841033/domains/ebfic.store/public_html/com/"
          SOURCE: "ebm_control/build/web/"
